const blogs = [
  {
    title: "C++ 指標入門",
    link: "https://sites.google.com/view/zhangcode-cppptr/c-%E6%8C%87%E6%A8%99?authuser=2",
    desc: "整理 C++ 指標、記憶體位址與 linked list 的基礎觀念，適合剛開始接觸資料結構的人。",
    img: "bp/blog2.jpg",
    category: "cs",
  },
  {
    title: "Linux 程式撰寫筆記",
    link: "https://sites.google.com/view/zhangcodelinuxcoding/linux?authuser=2",
    desc: "從 Linux 與 UNIX 的基本環境開始，記錄指令、編譯流程與開發時常見的操作細節。",
    img: "bp/blog3.jpg",
    category: "software",
  },
  {
    title: "APCS 2017-0304-3 解題紀錄",
    link: "https://sites.google.com/view/apcs2017-0304-3/%E9%A6%96%E9%A0%81?authuser=1",
    desc: "APCS 題目拆解與 AC 思路，包含資料處理、流程設計與容易出錯的地方。",
    img: "bp/apcs.jpg",
    category: "cs",
  },
  {
    title: "C++ 基礎學習整理",
    link: "https://sites.google.com/view/cppeasylearning/%E9%A6%96%E9%A0%81?authuser=1",
    desc: "用比較輕量的方式整理 C++ 入門觀念，包含語法、型別、流程控制與練習方向。",
    img: "bp/cppt.jpg",
    category: "software",
  },
  {
    title: "Computer Science 學習路線筆記",
    link: "posts/others001.html",
    desc: "整理學習資工基礎時的觀念地圖，從程式語言、資料結構到 bitmap 等底層表示方式。",
    img: "bp/CS.jpg",
    category: "cs",
  },
  {
    title: "Flask vs Django: What are their strengths?",
    link: "posts/python001.html",
    desc: "比較 Python 兩個常見 Web 框架的定位、適用場景與學習成本。",
    img: "bp/DVF.png",
    category: "software",
  },
  {
    title: "MySQL 入門筆記",
    link: "posts/others002.html",
    desc: "資料庫初學整理，包含資料表、查詢、關聯與實作時需要先理解的基本概念。",
    img: "bp/blog1.jpg",
    category: "software",
  },
  {
    title: ".dll 與 GCC 編譯概念",
    link: "posts/others003.html",
    desc: "記錄動態連結函式庫、編譯器與 C/C++ 開發流程中常見的環境問題。",
    img: "bp/others003.png",
    category: "software",
  },
  {
    title: "AI 工具與 YouTube 內容製作想法",
    link: "posts/others004.html",
    desc: "整理使用 AI 輔助內容產出的觀察，思考如何讓工具真正提升創作效率。",
    img: "bp/others004.png",
    category: "other",
  },
  {
    title: "OSI 七層模型筆記",
    link: "posts/others005.html",
    desc: "用初學角度拆解網路通訊層級，理解每一層負責的工作與常見名詞。",
    img: "bp/others005.png",
    category: "security",
  },
];
